#fram Garrett Gowe on Aug 4th, 2018

Asthma=sapply(1:nrow(sample_sam), function(i) switch(sample_sam[i,]$race,
                                                     "white"=switch(sample_sam[i,]$bracket.age,
                                                                    "0.to.5"=switch(sample_sam[i,]$sex,
                                                                                     "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.036, 0.964)),
                                                                                     "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.031, 0.969)), NA),
                                                                    "5.to.9"=switch(sample_sam[i,]$sex,
                                                                                    "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.138, 0.862)),
                                                                                    "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.111, 0.889)), NA),
                                                                    "10.to.14"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.138, 0.862)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.111, 0.889)), NA),
                                                                    "15.to.17"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.211, 0.789)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.176, 0.824)), NA),
                                                                    "18.to.19"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.211, 0.789)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.176, 0.824)), NA),
                                                                    "20.to.24"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.196, 0.804)),  
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.178, 0.822)), NA),
                                                                    "25.to.29"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.148, 0.852)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.175, 0.825)), NA),
                                                                    "30.to.34"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.148, 0.852)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.175, 0.825)), NA),
                                                                    "35.to.44"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.115, 0.885)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.166, 0.834)), NA),
                                                                    "45.to.54"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.115, 0.885)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.166, 0.834)), NA),
                                                                    "55.to.64"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.115, 0.885)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.166, 0.834)), NA),
                                                                    "65.to.74"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.131, 0.869)), NA),
                                                                    "75.to.84"=switch(sample_sam[i,]$sex,
                                                                                      "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                      "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.131, 0.869)), NA),
                                                                    "85.to.100"=switch(sample_sam[i,]$sex,
                                                                                     "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                     "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.131, 0.869)), NA)),
                                                     
                                                     "black"=switch(sample_sam[i,]$bracket.age,
                                                                                        "0.to.5"=switch(sample_sam[i,]$sex,
                                                                                                         "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.096, 0.904)),
                                                                                                         "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.1, 0.9)), NA),
                                                                                        "5.to.9"=switch(sample_sam[i,]$sex,
                                                                                                        "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.263, 0.737)),
                                                                                                        "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.241, 0.759)), NA),
                                                                                        "10.to.14"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.263, 0.737)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.241, 0.759)), NA),
                                                                                        "15.to.17"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.224, 0.776)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.22, 0.78)), NA),
                                                                                        "18.to.19"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.224, 0.776)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.22, 0.78)), NA),
                                                                                        "20.to.24"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.194, 0.806)),  
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.154, 0.846)), NA),
                                                                                        "25.to.29"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.163, 0.837)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.134, 0.866)), NA),
                                                                                        "30.to.34"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.163, 0.837)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.134, 0.866)), NA),
                                                                                        "35.to.44"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.181, 0.819)), NA),
                                                                                        "45.to.54"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.181, 0.819)), NA),
                                                                                        "55.to.64"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.181, 0.819)), NA),
                                                                                        "65.to.74"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.101, 0.899)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)), NA),
                                                                                        "75.to.84"=switch(sample_sam[i,]$sex,
                                                                                                          "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.101, 0.899)),
                                                                                                          "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)), NA),
                                                                                        "85.to.100"=switch(sample_sam[i,]$sex,
                                                                                                         "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.101, 0.899)),
                                                                                                         "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)), NA)),
                                                     
                                                     "hispanic"=switch(sample_sam[i,]$bracket.age,
                                                                                 "0.to.5"=switch(sample_sam[i,]$sex,
                                                                                                  "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.054, 0.946)),
                                                                                                  "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.08, 0.92)), NA),
                                                                                 "5.to.9"=switch(sample_sam[i,]$sex,
                                                                                                 "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.181, 0.819)),
                                                                                                 "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.101, 0.899)), NA),
                                                                                 "10.to.14"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.181, 0.819)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.101, 0.899)), NA),
                                                                                 "15.to.17"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.153, 0.857)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.118, 0.882)), NA),
                                                                                 "18.to.19"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.153, 0.857)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.118, 0.882)), NA),
                                                                                 "20.to.24"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.138, 0.842)),  
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.22, 0.78)), NA),
                                                                                 "25.to.29"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.098, 0.902)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.131, 0.869)), NA),
                                                                                 "30.to.34"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.098, 0.902)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.131, 0.869)), NA),
                                                                                 "35.to.44"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.073, 0.927)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.135, 0.865)), NA),
                                                                                 "45.to.54"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.073, 0.927)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.135, 0.865)), NA),
                                                                                 "55.to.64"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.073, 0.927)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.135, 0.865)), NA),
                                                                                 "65.to.74"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.044, 0.936)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.082, 0.918)), NA),
                                                                                 "75.to.84"=switch(sample_sam[i,]$sex,
                                                                                                   "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.044, 0.936)),
                                                                                                   "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.082, 0.918)), NA),
                                                                                 "85.to.100"=switch(sample_sam[i,]$sex,
                                                                                                  "Male" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.044, 0.936)),
                                                                                                  "Female" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.082, 0.918)), NA)),
                                                     
                                                     "asian"=switch(sample_sam[i,]$bracket.age,
                                                                    "0.to.5" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.04, 0.96)),
                                                                    "5.to.9" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.04, 0.96)),
                                                                    "10.to.14" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.04, 0.96)),
                                                                    "15.to.17" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.04, 0.96)),
                                                                    "18.to.19" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "20.to.24" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "25.to.29" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "30.to.34" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "35.to.44" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "45.to.54" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "55.to.64" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "65.to.74" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "75.to.84" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943)),
                                                                    "85.to.100" = sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.057, 0.943))),
                                                     
                                                     "multiracial"=switch(sample_sam[i,]$bracket.age,
                                                                                "0.to.5"= sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                "5.to.9"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                "10.to.14"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                "15.to.17"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.141, 0.859)),
                                                                                "18.to.19"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "20.to.24"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "25.to.29"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "30.to.34"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "35.to.44"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "45.to.54"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "55.to.64"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "65.to.74"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "75.to.84"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875)),
                                                                                "85.to.100"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.125, 0.875))), 
                                                     
                                                     "american.indian.or.alaskan"=switch(sample_sam[i,]$bracket.age,
                                                                                                "0.to.5"= sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)),
                                                                                                "5.to.9"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)),
                                                                                                "10.to.14"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)),
                                                                                                "15.to.17"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.161, 0.839)),
                                                                                                "18.to.19"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "20.to.24"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "25.to.29"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "30.to.34"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "35.to.44"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "45.to.54"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "55.to.64"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "65.to.74"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "75.to.84"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91)),
                                                                                                "85.to.100"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.09, 0.91))), 
                                                     
                                                     #Data collected from US Department of Health and Human Services, Department of Minority Health
                                                     "islander"=switch(sample_sam[i,]$bracket.age,
                                                                                                        "0.to.5"= sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.079, 0.921)),
                                                                                                        "5.to.9"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.079, 0.921)),
                                                                                                        "10.to.14"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.079, 0.921)),
                                                                                                        "15.to.17"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.079, 0.921)),
                                                                                                        "18.to.19"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "20.to.24"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "25.to.29"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "30.to.34"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "35.to.44"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "45.to.54"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "55.to.64"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "65.to.74"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "75.to.84"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901)),
                                                                                                        "85.to.100"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.099, 0.901))), 
                                                     
                                                     
                                                     "other.race"=switch(sample_sam[i,]$bracket.age,
                                                                              "0.to.5"= sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.127, 0.873)),
                                                                              "5.to.9"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.127, 0.873)),
                                                                              "10.to.14"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.127, 0.873)),
                                                                              "15.to.17"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.127, 0.873)),
                                                                              "18.to.19"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "20.to.24"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "25.to.29"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "30.to.34"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "35.to.44"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "45.to.54"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "55.to.64"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "65.to.74"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "75.to.84"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87)),
                                                                              "85.to.100"=sample(c("Yes", "No"), size = 1, replace = T, prob = c(0.013, 0.87))),
                                                     
                                                     
                                                     NA))

Asthma<-unlist(Asthma)
sample_sam$Asthma <- Asthma

